### ISSUE TITLE
Recursion problem

### ISSUE THREAD

**Issue by emmagras** [emmagras/hoo-will-build-the-roads#19]
Here's the traceback. I think it has to do with the instantiation distance buffer vs the "am I allowed to move from here" instantiation buffer.
One option is to limit the recursion to `n` steps, i.e. the car waits if it has no options. (probably optimal)
Another option (probably short term) is to widen the instantiation buffer/re-roll process, so cars start sufficiently far apart from each other. 
```
Traceback (most recent call last):
  File "git/hoo/hoo/main.py", line 45, in <module>
    main()
  File "git/hoo/hoo/main.py", line 41, in main
    simulate(**params.__dict__)
  File "/home/emma/git/hoo/hoo/simulation.py", line 11, in simulate
    [car.drive() for car in agents]
  File "/home/emma/git/hoo/hoo/simulation.py", line 11, in <listcomp>
    [car.drive() for car in agents]
  File "/home/emma/git/hoo/hoo/cars.py", line 126, in drive
    self.drive(speed=speed, direction=random.choice(range(-180, 181)))
  File "/home/emma/git/hoo/hoo/cars.py", line 126, in drive
    self.drive(speed=speed, direction=random.choice(range(-180, 181)))
....
    self.drive(speed=speed, direction=random.choice(range(-180, 181)))
  File "/home/emma/git/hoo/hoo/cars.py", line 119, in drive
    [x_loc, y_loc]])
  File "/home/emma/git/hoo/hoo/roads.py", line 24, in out_of_bounds
    for bound in self.relevant_bounds()])
  File "/home/emma/git/hoo/hoo/roads.py", line 24, in <listcomp>
    for bound in self.relevant_bounds()])
  File "/usr/local/lib/python3.4/dist-packages/shapely/geometry/base.py", line 641, in intersects
    return bool(self.impl['intersects'](self, other))
  File "/usr/local/lib/python3.4/dist-packages/shapely/predicates.py", line 13, in __call__
    self._validate(other, stop_prepared=True)
  File "/usr/local/lib/python3.4/dist-packages/shapely/topology.py", line 19, in _validate
    if stop_prepared and not hasattr(ob, 'type'):
  File "/usr/local/lib/python3.4/dist-packages/shapely/geometry/base.py", line 329, in type
    return self.geometryType()
  File "/usr/local/lib/python3.4/dist-packages/shapely/geometry/base.py", line 325, in geometryType
    return geometry_type_name(self._geom)
  File "/usr/local/lib/python3.4/dist-packages/shapely/geometry/base.py", line 49, in geometry_type_name
    return GEOMETRY_TYPES[lgeos.GEOSGeomTypeId(g)]
ctypes.ArgumentError: argument 1: <class 'RuntimeError'>: maximum recursion depth exceeded while calling a Python object
```

**Comment by emmagras** [comment]
pretty sure ccbebd3 closes this issue

**Comment by emmagras** [comment]
pretty sure ccbebd3 closes this issue
